# goreleaser.yml
project_name: clouddley

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: "clouddley"
    main: .
    binary: clouddley
    ldflags:
      - -s -w -X 'github.com/clouddley/clouddley/cmd.Version={{.Version}}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_{{ .Version}}_
      {{- if eq .Os "windows" }}Windows
      {{- else if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{- end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{- end }}
    builds:
      - "clouddley"

    format: tar.gz
    format_overrides:
      - format: tar.gz

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^ci"
