# goreleaser.yml
project_name: clouddley

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: "clouddley"
    main: .
    binary: clouddley
    ldflags: -s -w -X 'cmd.Version={{.Version}}'
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm64

archives:
  - id: "archive"

    builds:
      - "clouddley"

    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - dist/{{ .Binary }}_{{ .Os }}_{{ .Arch }}/*.gz # Include the gzipped binaries

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
