name: Go Build and Test

on:
  push:
    branches:
      - main # Run tests automatically on pushes to the main branch
    paths-ignore:
      - "**.md" # Ignore markdown files

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21 # Adjust this to match your project's Go version

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
